config/routes.rb
Rails.application.routes.draw do
  get '/posts/funny' , to: 'posts#funny'
  get '/posts/popular', to: 'posts#popular'
  devise_for :users
  resources :posts do
    resources :comments do
      resources :subcomments
    end
  end
  get '/home', to: 'home#home'
  root 'posts#index'

  resources :posts do
    resources :votes, only: [:create,:update, :destroy]
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :subcomments , dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  before_action :find_comment, only: [:destroy]
  before_action :authenticate_user!, except:[:show]
  load_and_authorize_resource
  def index
    @comments=Comment.all
  end
  def create
    @comment=@post.comments.create(comment_params)
    @comment.user_id=current_user.id
    @comment.save
    if @comment.save
      redirect_to post_path(@post)
    end
  end
  def show
    @comment=Comment.find(params[:id])
    @subcomments=Subcomment.where(comment_id: @comment).order("created_at DESC")
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post), notice:'Comment deleted'
  end

  private
  def find_post
    @post=Post.find(params[:post_id])
  end

  def find_comment
    @comment=@post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="comments_form">
<%= form_for([@post,@post.comments.build]) do |f|%>
 <%= f.text_area :content %>
 <%= f.submit %>
 <%end%>
</div>

app/views/comments/index.html.erb
<%=render "comments/form" %>
<% @comments.each do |comment| %>
  <%var=comment.user_id%>
  <%user=User.find(var)%>
  <%comment_username=user.username%>
  <div class="comment">
  <p class="comment_content">" <%= comment.content %> "</p>
  <div class="under_comment">
  <p class="username"><strong><%=comment_username%></p></strong>
  <p><%= time_ago_in_words(comment.created_at) %> ago</p>
  <% if comment.user==current_user %>
  <p><%= link_to 'delete', [comment.post,comment],method: :delete, :class=>'delete'%></p>
  <p><%= link_to 'leave comment' , post_comment_path(@post, comment)	 %>
  </p>
  <%end%>
  </div>
  </div>
  </div>
<%end%>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Comments</h2>
<div class="comment">
<%= @comment.content %>
</div>
<div class="subcomments_form">
<%= form_for([@post,@comment, @comment.subcomments.build]) do |f|%>
 <%= f.text_area :content %>
 <%= f.submit %>
 <%end%>
</div>
<div class="subcomment">
 <% @subcomments.each do |subcomment|%>
 <%= subcomment.content %>
 <p><%= link_to 'delete', [@post,@comment,subcomment] , method: :delete %>
 <%end%>
</div>
<%= link_to 'back', post_path(@post) %>